version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - rabbitmq
      - frontend

  celery:
    build: .
    command: celery -A quiz.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  redis-data:
  rabbitmq-data:
