name: CI Pipeline

on:
  push:
    branches:
      - main
      - fronted
      - backend
  pull_request:
    branches:
      - main
      - fronted
      - backend

jobs:
  test-backendend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/backend' || github.ref == 'refs/heads/main' # Запускается только для веток backend и main

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432
        volumes:
          - /var/lib/postgresql/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgres://myuser:mypassword@localhost/mydb
        run: |
          python backend/manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: postgres://myuser:mypassword@localhost/mydb
        run: |
          python backend/manage.py migrate

  test-frontedend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/fronted' || github.ref == 'refs/heads/main' # Запускается только для веток fronted и main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Run frontedend tests
        run: |
          npm run test
