name: CI Pipeline

on:
  push:
    branches:
      - main
      - frontend
      - backend
  pull_request:
    branches:
      - main
      - frontend
      - backend

jobs:
  test-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/backend' || github.ref == 'refs/heads/main'

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgres://myuser:mypassword@db/mydb
        run: |
          python backend/manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: postgres://myuser:mypassword@db/mydb
        run: |
          python backend/manage.py test

  test-frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/frontend' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
        working-directory: ./frontend

      - name: Run frontend tests
        run: |
          npm run test
        working-directory: ./frontend
