# Generated by Django 4.2 on 2024-11-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('player_count', models.PositiveIntegerField()),
                ('theme', models.CharField(max_length=100)),
                ('answer_time', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(max_length=255)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('correct_answers_count', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='room.room')),
            ],
            options={
                'unique_together': {('user', 'room', 'user_agent')},
            },
        ),
    ]
