# Generated by Django 4.2 on 2024-11-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0005_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='room',
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.CharField(default='Спорт', max_length=100),
            preserve_default=False,
        ),
    ]
