# Generated by Django 4.2 on 2024-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0008_roomparticipant_current_question_index_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='correct_answers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
